---
title: "STAT112 - Spotify Final Project"
author: "Brian Lee, Alex Ismail, Malek Kaloti"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading packages
library(lubridate)
library(dplyr)
library(tidyverse)
```

```{r}
#loading data
spotify <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv')

spotify_rap <- spotify %>% 
  filter(playlist_genre == "rap")
```

## Prelim Graph

```{r}
prelim_graph <- spotify %>%
  ggplot(aes(y = playlist_genre, x = track_popularity)) +
  labs(title = "Song Popularity by Genre",
       x = "", y = "",
       subtitle = "Song popularity is measured from 0-100, with higher numbers being indiciative of more popularity.\nHighest median popularities belong to pop and latin with an overall median popularity of 40",
       caption = "Alex Ismail, Malek Kaloti, Brian Lee") +
  theme_classic() + 
  theme(plot.title.position = "plot",
        plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 10, face = "italic")) +
  geom_boxplot() +
  geom_vline(aes(xintercept = median(track_popularity, na.rm = TRUE)), color = "blue") 

prelim_graph
```



```{r}
spotify %>% 
  mutate(track_name_lower = str_to_lower(track_name),
         remix = str_detect(track_name_lower, "Remix"),
         feature = str_detect(track_name_lower, "feat"),
         ma_prep = remix|feature,
         ma_prep2 = replace_na(ma_prep, FALSE),
         multiple_artists = if_else(ma_prep2, true = "Multiple Artists", false = "One Artist"),
         popular = track_popularity > 75) %>% 
  group_by(multiple_artists, playlist_genre) %>% 
  summarize(prop_pop = mean(popular)*100) %>% 
  mutate(genre = fct_relevel(playlist_genre, "rap")) %>% 
  ggplot() +
  geom_col(aes(x = multiple_artists, y = prop_pop)) +
  facet_wrap(~genre) +
  labs(title = "Popularity of Songs Containing Mulitple Artists Across Genre",
       x = "", y = "Percent of Songs Popular") +
  theme_classic() + 
  theme(plot.title.position = "plot",
        plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 10, face = "italic"))
```


```{r}
spotify_rap %>% 
  mutate(Rounded_Danceability = round(danceability, digits = 1),
         Rounded_Energy = round(energy, digits = 1),
         Rounded_Speechiness = round(speechiness, digits = 1),
         Rounded_Instrumental = round(instrumentalness, digits = 1),
         popular = track_popularity > 75) %>% 
  pivot_longer(cols = starts_with("Rounded"),
               names_to = "Stat1",
               values_to = "Rounded_Value") %>% 
  group_by(Stat1, Rounded_Value) %>% 
  summarize(Pop_Rate = mean(popular)*100) %>% 
  mutate(Stat = fct_recode(Stat1, 
                             Danceability = "Rounded_Danceability",
                             Energy = "Rounded_Energy",
                             Speechiness = "Rounded_Speechiness",
                             Instrumental = "Rounded_Instrumental")) %>% 
  ggplot(aes(x = Rounded_Value, y = Pop_Rate)) +
  geom_line(aes(color = Stat)) +
  labs(title = "Popularity of Rap Songs by Song Characteristic",
       x = "", y = "Percent Popular", color = "Song Statistic") +
  theme_classic() + 
  theme(plot.title.position = "plot",
        plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 10, face = "italic"))
```


